<a href="https://colab.research.google.com/github/Frankzhf0216/Build-up-linear-regression-hypothesis-regarding-two-features/blob/master/CS483_Homework6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS483_HomeWork4_Q2


In [1]:
!pip install hmmlearn

     |████████████████████████████████| 368kB 2.7MB/s 


In [19]:
import numpy as np
from hmmlearn import hmm

states = ["bottle 1", "bottle 2", "bottle 3"]
n_states = len(states)   # =3

observations = ["red", "yellow", "green"]
n_observations = len(observations)

start_probability = np.array([0.4, 0.35, 0.25])

transition_probability = np.array([
  [0.3, 0.2, 0.5],
  [0.1, 0.3, 0.6],
  [0.7, 0.25, 0.05]
])

emission_probability = np.array([
  [0.8, 0.1, 0.1],
  [0.2, 0.4, 0.4],
  [0.15, 0.25, 0.6]
])

model = hmm.MultinomialHMM(n_components=n_states) 
# MultinomialHMM: observation distribution in Multinomial
model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability

seen = np.array([[0,0,1,2,1]]).T        # 0: red;     1: yellow     2: green   => r r y g y
logprob, box = model.decode(seen, algorithm="viterbi")
seen = [0,0,1,2,1]
print("The candy picked:", ", ".join(map(lambda x: observations[x], seen)))
print("The bottle:", ", ".join(map(lambda x: states[x], box)))

The candy picked: red, red, yellow, green, yellow
The bottle: bottle 1, bottle 1, bottle 2, bottle 3, bottle 2


In [20]:
seen = np.array([[0,0,1,2,1]]).T 
box2 = model.predict(seen)      # same as "viterbi"
seen = [0,0,1,2,1]
print("The candy picked:", ", ".join(map(lambda x: observations[x], seen)))
print("The bottle:", ", ".join(map(lambda x: states[x], box2)))

The candy picked: red, red, yellow, green, yellow
The bottle: bottle 1, bottle 1, bottle 2, bottle 3, bottle 2


In [21]:
seen = np.array([[0,0,1,2,1]]).T                  # P(rrygy) =?
print(model.score(seen))
# ln(P(red*red*yellow*green*yellow)) = -5.935089171594137   # P(rrygy) = exp(-5.935089171594137)

-5.935089171594137


In [22]:
import numpy as np
from hmmlearn import hmm

states = ["box 1", "box 2", "box3"]
n_states = len(states)

observations = ["red", "yellow", "green"]
n_observations = len(observations)
model2 = hmm.MultinomialHMM(n_components=n_states, n_iter=20, tol=0.01)
X2 = np.array([[0,0,1,2,1],[0,1,1,2,0],[2,1,0,1,2]])
model2.fit(X2)
print(model2.startprob_)
print(model2.transmat_)
print(model2.emissionprob_)
print(model2.score(X2))
model2.fit(X2)
print(model2.startprob_)
print(model2.transmat_)
print(model2.emissionprob_)
print(model2.score(X2))
model2.fit(X2)
# print(model2.startprob_)
# print(model2.transmat_)
# print(model2.emissionprob_)
# print(model2.score(X2))

[2.6045138e-38 5.4736090e-41 1.0000000e+00]
[[1.66834580e-001 8.33165420e-001 2.84524544e-012]
 [8.32357991e-001 1.00274393e-117 1.67642009e-001]
 [3.53754328e-014 1.00000000e+000 8.03985302e-025]]
[[6.62632712e-05 9.99933737e-01 7.39516769e-17]
 [4.28570020e-01 1.19871086e-38 5.71429980e-01]
 [9.96894536e-01 3.10546374e-03 5.25293494e-53]]
-10.190441306174737
[1.00000000e+00 3.39842387e-20 1.15965855e-25]
[[7.69999404e-25 1.00000000e+00 2.87588454e-12]
 [1.56195816e-01 5.31800272e-49 8.43804184e-01]
 [3.43351384e-17 8.34275776e-01 1.65724224e-01]]
[[9.99941163e-01 5.88372466e-05 1.81543842e-38]
 [4.28356613e-01 1.43638587e-15 5.71643387e-01]
 [1.08773314e-02 9.89122669e-01 1.70997162e-12]]
-10.205406402542181


MultinomialHMM(algorithm='viterbi', init_params='ste', n_components=3,
               n_iter=20, params='ste',
               random_state=RandomState(MT19937) at 0x7F6E4A4FF678,
               startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
               verbose=False)